### ISSUE TITLE
General feature breakdown

### ISSUE THREAD

**Issue by krames12** [jemagee/code_connection#1]
## Purpose of this issue
I believe that breaking down the wants and needs of this projects would be a beneficial exercise to start to make things a bit more manageable and obtainable.

## Format
 - ### Main Feature Heading
 - #### Sub Feature Heading

### Personal Profile
  - #### Traits
  - #### Qualities
  - ### Projects
    - Owned
    - Participating In
### Project 'Marketplace'
  - ### Search projects
  - ### View projects
  - ### Filter projects by tech / role(?)
  - ### Project creation

## Notes
From what I can gather, this is a somewhat descriptive breakdown of what the project would require based on the `What Do I want Code Connection to do?` section. I'm not quite sure what exactly would be under `Traits` and `Qualities`, but I figure it would be something along the lines of tech you are comfortable with and/or want to learn. 

I would love to see this get hashed out a bit more by others on a feature by feature basis before we even think about the tech that would be involved minus the obvious front end stuff like HTML, CSS and Javascript.

**Comment by jemagee** [comment]
Well first off, that's a terrible paragraph I wrote:

_I think it's pretty simple. I want Code Connection to connect people. I want people to be able to fill out not only a profile of their traits, qualities, but a profile of traits qualities they're looking for._

I realize that's important to clarify because having a clear registration model is vital to getting active users.

(The following information is the least bad explanation I've written to try and explain the idea better, sorry)

So let's take me for example

* I'm looking for people to work with, even online, learning things we can't all go to the local coffee shop but maybe we can link people online to a slack channel or something (no cost to them)
  * List what I want to learn, and what I already know, be it language, or TDD, QA, UI/UX
  * List availability, days of the week, time frames, etc...
  * List preferred methods of working together (if options exist)
  * List if interested in doing any sort of paid tutorials together?
* I'm looking for projects to contribute to:
   * What sort of things do I want to work on
   * What sort of languages do i want to work on
   * Perhaps we could even say what sort of 'type' of projects people might want to work on if we can categorize them?
* These are my skill sets
  * Languages / Libraries / level of ability
  * Areas (UI/UX, TDD, QA, DDL, query writing, etc...) and level of ability
* These are the skill sets I feel qualified to help people with
* These are the skill sets I want to get better at

I don't want to over do personal information, peoplle need a valid email address and a username, but I'm not for collecting lots of information, most other stuff will be optional (portfolio, git hub, twitter, whatever)

I don't want to get into the project market place just yet - perhaps it should even be a separate issue - ooh - perhaps we could have issues to discuss the various components ideas.

I will want to change the read me based on what we agree upon here but hope for more input as well.  More points of view the better.

**Comment by dentemple** [comment]
Perhaps a good feature would be for something like an active lobby for people to drop in on?  

Sort of like the kind of waiting lobby you'd see in a multiplayer game.  Projects that are "live" would have open connections from this lobby to the project's respective github and gitter links, and project owners can interact with the people in-lobby to socialize or recruit.  For people in the lobby, they can socialize and review the active projects available.

You probably woudn't have to go as far as turning it into a twitch.tv clone; the projects themselves don't have to be "live" as in "recording" live... just "live" as in "the contributors have scheduled a few hours where they can be open and available for discussion and help."

This feature might give this project more traction, and it would make it feel more like just another "OSS Looking For Contributors" board.

Just a thought :)

**Comment by jemagee** [comment]
dentemple I do like the thought, it's involved, and beyond my even comprehension right now (though maybe action cable works)...right now I'm still trying to work out the basics of version 1.0 but the lobby is a good 2.0 thing - if the lobby was fancy we could have 'buttons' on the people in the lobby that indicates what they're good at and / or looking for - it's not really a 'flea market' so much but the idea that everyone can find what they need be it programming partners in the same time zone, skill level, or projects to work on - that would be great - plus - there's probably some smart way to use a gem or something so that we could link peoples projects on the site to their version control project and give updates on activity / issues / etc...though i'd also want people to be more aggressive in tagging stuff in regards to difficulty and specificially focus

**Comment by jemagee** [comment]
I'm going to close this, and save it for later as there is a lot of meat in there, but I've fallen down on the job in moving this project forward, and as such, I started the application and updated the repository, and hopefully those originally interested will still be interested.
